"use client"
import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local"; // cài vào trong source code để sử dụng bằng cách tải font về và bỏ vào folder app ví dụ ở đây là roboto-thin.ttf
// import { Roboto } from "next/font/google"; lấy font từ google mà không cần add link vào thẻ head
import { ThemeProvider } from '@mui/material/styles';
import CssBaseline from '@mui/material/CssBaseline';
import { theme } from '@/lib/theme';
import { MenuDialog } from '@/components/MenuDialog';

// const roboto = Roboto({ subsets: ["vietnamese"], weight: ["100", "300"] });

const myFont = localFont({
  src: [
    // {
    //   path: "./Roboto-Regular.ttf",
    //   weight: "100",
    // },
    {
      path: "./Roboto-Thin.ttf",
      weight: "400",
    },
  ],
  display: "swap",
  variable: "--font-roboto", // font-tailwind
});

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap"
          rel="stylesheet"
        />
      </head> */}

      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        className={`${myFont.className} ${myFont.variable}`}
      >
        <ThemeProvider theme={theme}>
          <CssBaseline />
          <MenuDialog />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
